#ifndef PATIENT_H
#define PATIENT_H

#include "iostream"
#include "set"
#include "person.hpp"
using namespace std;

class Patient :public Person
{ //  :: it takes
private:
    static set<string>UniqueIDs;
public:
    string disease;
    string patientID;
    Patient();
    Patient(string name, int age, string contact, string patientID, string disease);
    void static updatePatientInfo(Patient&,string name, int age, string contact, string patientID, string disease);
    void getDetails() override;
    void static saveToFile(const Patient&);
    void static loadFromFile();

}; // Patient class

// error class generated by the Patient class
class UniquePatientID : public runtime_error
{
public:
    UniquePatientID(const char *message):runtime_error(message){}
};

class FileNotOpening : public runtime_error
{
public:
    FileNotOpening(const char *message):runtime_error(message){}
};

#endif