#ifndef PATIENT_H
#define PATIENT_H

#include "iostream"
#include "set"
#include "../include/person.hpp"
using namespace std;

class Patient : Person
{ //  :: it takes
private:
    static set<string>UniqueIDs;
    void static loadIds();
    void static saveids();
protected:
    char disease[31];
    char patientID[13];

public:
    Patient();
    Patient(string name, int age, string contact, string patientID, string disease);
    void registerPatient(string patientID, string disease);
    void updatePatientInfo(string name, int age, string contact, string patientID, string disease);
    void getPatientDetails();
    void static saveToFile(const Patient&);
    void static loadFromFile(const string patientID);
    void static loadFromFile();
    size_t sizeOf() const;

}; // Patient class

// error class generated by the Patient class
class UniquePatientID : public runtime_error
{
public:
    UniquePatientID(const char *message):runtime_error(message){}
};

class FileNotOpening : public runtime_error
{
public:
    FileNotOpening(const char *message):runtime_error(message){}
};

#endif